author = "Tilen Gimpelj"
studij = "Bioinformatika"

naslov = "Matematični model bioreaktorja z dohranjevanjem"
title = "Mathematical model of a fed-batch bioreactor"
text_lang = "en"
kljucne_besede = ["bioreaktor", "modeliranje", "Runge-Kutta", "Nelder-Mead", "NDE", "simulacija"]
key_words = ["bioreactor", "modeling", "Runge-Kutta", "Nelder-Mead", "ODE", "simulation"]

[mentor]
name = "Aleksander Tošić"
sl = ["izr. prof. dr. ", ""]
en = ["Assoc. Prof.",", PhD"]
[somentor]
name = "Domen Vake"
sl = ["",""]
en = ["",""]
[work_mentor]
name = "Andrej Pohar"
sl = ["dr.",""]
en = ["",", PhD"]


[kratice]
"GMP" = "Good manufacturing practices"
"CHO" = "Chinese hamster ovary"
"rCHO" = "recombinant Chinese hamster ovary"
"DNA" = "Deoxyribonucleic acid"
"SF" = "Serum free"
"FDA" = "Food and Drug Administration"
"BHK" = "Baby hamster kidney"
"HEK" = "Human embryonic kidney"
"GMO" = "Geneticly modified organism"
"EMEM" = "Eagle's minimum essential medium"
"PUMS" = "Peking Union Medical School"
"PUMC" = "Peking Union Medical College"
"ODE" = "Ordinary differential equation"
"LDE" = "Linear differencial equation"
"RK" = "Runge-Kutta"
"UI" = "User interface"
"VCD" = "Viable cell density"
"PID" = "Proportional integral derivative"
"DO" = "Dissolved oxygen"
"OTR" = "Oxygen transfer rate"
"OUR" = "Oxygen uptake rate"
"kLa" = "Volumetric mass transfer coefficient"